### PR TITLE
added add to calender button

### LINKED ISSUE #32: Option to add event to Google calendar
App might require supporting all educational email accounts, a button of calendar to invite and add event to your calendar easily.

### PR DESCRIPTION
**Pull request by code-ash-IIT**
Fixes #32 . Support for multiple calenders.
Screenshot 2021-12-15 at 3 21 42 PM
Screenshot 2021-12-15 at 3 21 50 PM
Screenshot 2021-12-15 at 3 22 07 PM

### CODE REVIEW

**Comment by code-ash-IIT** [comment]
@LalitNM @abhijeetmanhas

**Comment by abhijeetmanhas** [comment]
Thanks for the change

**Review by abhijeetmanhas — APPROVED** [review]

**Comment by abhijeetmanhas** [comment]
@code-ash-IIT can you please ensure that the calendar icon is in centre of small white rectangle?
Also, we are using add to event plugin here, which has limited use. Please make something from scratch, maybe just for gmeet. And also trim the long urls

**Comment by code-ash-IIT** [comment]
@abhijeetmanhas okk, will look into it.

**Pull request merged**
